server:
  port: 8964

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hobby?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mohistzh


mybatis:
  mapper-locations:
    classpath: mapper/*.xml
    type-aliases-package: me.mohistzh.tinyurl.pojo
